title: Anveshanam
logo: /static/anveshanamLOGO.png
description: Research Society Club of IIT Gandhinagar. 
google_analytics:
theme: jekyll-theme-minimal
affiliation: Indian Institute of Technology Gandhinagar
email: anveshanam (at) iitgn.ac.in
another_url: another value

linkedin: https://www.linkedin.com/in/himanshubeniwal/
twitter: https://twitter.com/HimanshuBeniwaI

<a href="your-link">👔 LinkedIn</a>
