title: Himanshu Beniwal
logo: /static/simple2.png
description: PhD Student (Prime Minister Research Fellow) at IIT Gandhinagar, India.
google_analytics:
theme: jekyll-theme-minimal
affiliation: Indian Institute of Technology Gandhinagar
email: himanshubeniwal (at) iitgn.ac.in
another_url: another value

keywords: minimal academic
canonical: https://minimal-light.yyliu.net/

lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: 👨🏻‍💻 # the emoji used as the favicon
remote_theme: yaoyao-liu/minimal-light

google_scholar: https://scholar.google.co.in/citations?user=wXkqUU8AAAAJ&hl=en
github_link: https://github.com/himanshubeniwal/
linkedin: https://www.linkedin.com/in/himanshubeniwal/
twitter: https://twitter.com/HimanshuBeniwaI

enable_google_analytics:    true  # enables google analytics
enable_panelbear_analytics: true  # enables panelbear analytics
enable_google_verification: false  # enables google site verification
enable_bing_verification:   false  # enables bing site verification
enable_mansory:             true   # enables automatic project cards arangement
enable_math:                true   # enables math typesetting (uses MathJax)
enable_tooltips:            false  # enables automatic tooltip links generated
                                   # for each section titles on pages and posts
enable_darkmode:            false   # enables switching between light/dark modes
enable_navbar_social:       false  # enables displaying social links in the
                                   # navbar on the about page
enable_project_categories:  true   # enables categorization of projects into
                                   # multiple categories
enable_medium_zoom:         true   # enables image zoom feature (as on medium.com)

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
